// TCP + TLS NDJSON transport for the fake gateway (PROTOCOL.md §1), so real clients such as
// research/probe.py can talk to it. One line per message; lines over 64 KiB close the connection;
// a client more than about 4 MB behind on reading is dropped. The certificate is generated by
// whoever starts it (tests do it at test time); none is committed.
import { createServer, type TLSSocket } from 'node:tls';
import { StringDecoder } from 'node:string_decoder';
import type { FakeGateway } from './gateway.ts';

export interface TlsOptions {
  key: string | Buffer;
  cert: string | Buffer;
  host?: string; // default 127.0.0.1: the fake is not for the open network
  port?: number; // default 0: any free port
}

export interface TlsServer {
  readonly port: number;
  close(): Promise<void>;
}

export async function listenTls(gw: FakeGateway, opts: TlsOptions): Promise<TlsServer> {
  const sockets = new Set<TLSSocket>();
  const { maxLineBytes, maxBehindBytes } = gw.behaviour;

  const server = createServer({ key: opts.key, cert: opts.cert }, (socket) => {
    sockets.add(socket);
    const decoder = new StringDecoder('utf8');
    let buf = '';
    let open = true;
    const conn = gw.attach({
      write(line) {
        if (!open) return;
        if (socket.writableLength > maxBehindBytes) { open = false; socket.destroy(); return; } // §1: slow reader
        socket.write(line + '\n');
      },
      close() {
        if (!open) return;
        open = false;
        socket.end();
      },
    });
    socket.on('data', (chunk: Buffer) => {
      buf += decoder.write(chunk);
      for (let i = buf.indexOf('\n'); i >= 0 && open; i = buf.indexOf('\n')) {
        const line = buf.slice(0, i);
        buf = buf.slice(i + 1);
        conn.receive(line.endsWith('\r') ? line.slice(0, -1) : line);
      }
      if (open && Buffer.byteLength(buf, 'utf8') > maxLineBytes) conn.receive(buf); // over-long: the gateway closes
    });
    socket.on('close', () => {
      open = false;
      sockets.delete(socket);
      conn.disconnect();
    });
    socket.on('error', () => { /* 'close' follows and tidies up */ });
  });

  await new Promise<void>((resolve, reject) => {
    server.once('error', reject);
    server.listen(opts.port ?? 0, opts.host ?? '127.0.0.1', () => resolve());
  });
  const addr = server.address();
  const port = typeof addr === 'object' && addr ? addr.port : 0;

  return {
    port,
    close: () => new Promise<void>((resolve) => {
      for (const s of sockets) s.destroy();
      server.close(() => resolve());
    }),
  };
}
